language: csharp
mono: none
dotnet: 2.0.0

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - sudo apt-get -qq update && sudo apt-get install -y tor 
        - echo $(sudo killall tor)
        - tor RunAsDaemon 1
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker pull lontivero/bitcoin-regtest
        - docker run -it -p 18332:18332 -p 8332:8332 lontivero/bitcoin-regtest /bin/bash -c "bitcoind -datadir=/home/bitcoind-regtest/node"
    - os: osx
      sudo: required
      services:
        - docker
      before_install:
        - ulimit -S -n 4096
        - brew install tor; 
        - echo $(sudo killall tor)
        - tor RunAsDaemon 1
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker pull lontivero/bitcoin-regtest
        - docker run -it -p 18332:18332 -p 8332:8332 lontivero/bitcoin-regtest /bin/bash -c "bitcoind -datadir=/home/bitcoind-regtest/node"

script:
  - sleep 5
  - travis_wait dotnet test MagicalCryptoWallet.Tests/MagicalCryptoWallet.Tests.csproj
